import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Button, Input, Modal } from '@deepseek-ai/dsh-client-ui-primitives';
import css from './CloudDiskPage.module.css';
/**
 * Renders the standalone local-credential connection view.
 * @param props - Connection state and user actions supplied by the CloudDisk page.
 * @returns Centered connection management controls.
 */
function CloudDiskConnectionPanel(props) {
    const { t, apiKey, signingSecret, apiKeyConfigured, signingSecretConfigured, connecting, failure, confirmDisconnect, canReturnToDisk, user, showCredentialFields, onApiKeyChange, onSigningSecretChange, onConnect, onStartDisconnect, onDisconnect, onCancelDisconnect, onReturnToDisk, onShowCredentialFields, } = props;
    return _jsxs("section", { className: css.connectionPanel, "aria-labelledby": "cloud-disk-setup-title", children: [_jsx("p", { className: css.connectionProduct, children: t('title') }), _jsx("h1", { id: "cloud-disk-setup-title", children: t('setupTitle') }), canReturnToDisk && user !== undefined && !showCredentialFields
                ? _jsxs("section", { className: css.connectionStatus, "aria-label": t('connectionStatus'), children: [_jsx("p", { children: t('connectionStatus') }), _jsx("strong", { children: user }), _jsx("span", { children: t('connected') })] })
                : _jsxs(_Fragment, { children: [_jsx("p", { className: css.connectionDescription, children: t('setupDescription') }), _jsxs("label", { children: [t('apiKey'), _jsx(Input, { type: "password", autoComplete: "off", value: apiKey, onChange: event => onApiKeyChange(event.target.value), placeholder: apiKeyConfigured ? t('configured') : t('apiKey') })] }), _jsxs("label", { children: [t('signingSecret'), _jsx(Input, { type: "password", autoComplete: "off", value: signingSecret, onChange: event => onSigningSecretChange(event.target.value), placeholder: signingSecretConfigured ? t('configured') : t('signingSecret') })] })] }), failure !== undefined && _jsx("p", { role: "alert", children: failure }), _jsxs("div", { className: css.connectionActions, children: [showCredentialFields ? _jsx(Button, { disabled: connecting, onClick: onConnect, children: connecting ? t('connecting') : t('connect') }) : _jsx(Button, { disabled: connecting, onClick: onShowCredentialFields, children: t('updateCredentials') }), apiKeyConfigured || signingSecretConfigured ? _jsx(Button, { disabled: connecting, onClick: onStartDisconnect, children: t('disconnect') }) : null, canReturnToDisk ? _jsx(Button, { disabled: connecting, onClick: onReturnToDisk, children: t('returnToDisk') }) : null] }), _jsx(Modal, { open: confirmDisconnect, onClose: onCancelDisconnect, title: t('disconnectTitle'), closeLabel: t('cancel'), description: t('disconnectWarning'), footer: _jsxs(_Fragment, { children: [_jsx(Button, { disabled: connecting, onClick: onCancelDisconnect, children: t('cancel') }), _jsx(Button, { disabled: connecting, onClick: onDisconnect, children: t('confirmDisconnect') })] }) })] });
}
export { CloudDiskConnectionPanel };
//# sourceMappingURL=CloudDiskConnectionPanel.js.map